### ISSUE TITLE
Is there a way to use other players?

### ISSUE THREAD

**Issue by ghost** [skeeto/transcription-mode#3]
Love it! Started using it today to annotate recordings of lectures.

Wondering if it can work (potentially) with other players (on Linux at least)?

**Comment by skeeto** [comment]
The mode relies exclusively on VLC's rc interface:
https://wiki.videolan.org/documentation:modules/rc/

The other media player would need to support the same text-driven 
interface on stdin. Otherwise the mode would have to be coded for an 
entirely different interface (TCP? RPC?). I don't know of any other 
media players with such a rich enough (by default) remote control 
interface. Did you have one in mind?

**Comment by ghost** [comment]
Yes, I thought that would be an issue... It'd be easier if it'd simply use the default system player, in case you don't have VLC installed (which is typically not the default), but clearly this is not a "deal breaker". It's incredibly useful to me as is!
